spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/exam?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    redis:
      host: 139.224.49.108
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 10
          min-idle: 0

server:
  servlet:
    context-path: /api